name: toby_bills
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  window_manager: ^0.2.7
  flutter_styled_toast: ^2.1.3
  get_storage: ^2.0.3
  dio: ^4.0.6
#  flutter_typeahead:
  intl: ^0.17.0
  dropdown_search: ^5.0.3
  excel: ^2.0.0-null-safety-3
  pdf: ^3.8.3
  path_provider: ^2.0.11
  printing: ^5.9.3
  multiselect: ^0.0.7
  desktop_multi_window: ^0.2.0
  flutter_keyboard_visibility: ^5.4.0
  file_picker: ^5.2.3
  firedart: ^0.9.0+1
  percent_indicator: ^4.0.1
  syncfusion_flutter_charts: ^20.4.48


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  fonts:
    - family: CairoBold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 600
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 500